/**
 *  2023/02/01 운영서버 반영 완료
 */
/*
/*
 * 테이블 백업 후 재생성  
 */
-- 테이블 백업
CREATE TABLE TB_RCPER_LVLH_GRD_BAK
AS SELECT * FROM TB_RCPER_LVLH_GRD;

CREATE TABLE TB_DMGE_GRD_MNG_BAK
AS SELECT * FROM TB_DMGE_GRD_MNG;

/* 기존 테이블 삭제 */
DROP TABLE TB_RCPER_LVLH_GRD CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_RCPER_LVLH_GRD_HST CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_DMGE_GRD_MNG CASCADE CONSTRAINTS PURGE;

--DROP TABLE TB_ABSTRCT_ADDR CASCADE CONSTRAINTS PURGE;

CREATE TABLE TB_ABSTRCT_ADDR
(
    SN                   NUMBER(10) NOT NULL ,
    SUFRER_NO            NUMBER(10) NULL ,
    ABSTRCT_ADDR         VARCHAR2(200) NULL ,
    DCLR_YR              CHAR(4) NULL ,
    DCLR_RESN            VARCHAR2(200) NULL ,
    GAP_DSTNC            NUMBER(10,3) NULL ,
    LAT                  NUMBER(12,10) NULL ,
    LOT                  NUMBER(13,10) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_ABSTRCT_ADDR
    ADD CONSTRAINT  PK_TB_ABSTRCT_ADDR PRIMARY KEY (SN);


CREATE TABLE TB_DMGE_GRD_MNG
(
    DMGE_GRD_YR          CHAR(4) NOT NULL ,
    DMGE_GRD_CD          VARCHAR2(10) NOT NULL ,
    CRTR_INCOME_AMT      NUMBER(15) NULL ,
    SVRTY_BGNG_SCRE      NUMBER(5,2) NULL ,
    SVRTY_END_SCRE       NUMBER(5,2) NULL ,
    GRD_RATE             NUMBER(5,2) NULL ,
    GRD_AMT              NUMBER(15) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_DMGE_GRD_MNG
    ADD CONSTRAINT  PK_TB_DMGE_GRD_MNG PRIMARY KEY (DMGE_GRD_YR,DMGE_GRD_CD);


CREATE TABLE TB_RCPER_LVLH_GRD
(
    BIZ_AREA_CD          VARCHAR2(10) NOT NULL ,
    BIZ_ODER             NUMBER(3) NOT NULL ,
    EXMN_ODER            NUMBER(3) NOT NULL ,
    APLY_NO              VARCHAR2(10) NOT NULL ,
    DISS_KND_CD          VARCHAR2(30) NOT NULL ,
    SVRTY_SCRE           NUMBER(5,2) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_RCPER_LVLH_GRD
    ADD CONSTRAINT  PK_TB_RCPER_LVLH_GRD PRIMARY KEY (BIZ_AREA_CD,BIZ_ODER,EXMN_ODER,APLY_NO,DISS_KND_CD);

CREATE TABLE TB_RCPER_LVLH_GRD_HST
(
    HST_NO               NUMBER(10) NOT NULL ,
    BIZ_AREA_CD          VARCHAR2(10) NULL ,
    BIZ_ODER             NUMBER(3) NULL ,
    EXMN_ODER            NUMBER(3) NULL ,
    APLY_NO              VARCHAR2(10) NULL ,
    DISS_KND_CD          VARCHAR2(30) NULL ,
    SVRTY_SCRE           NUMBER(5,2) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL ,
    LOG_TY               VARCHAR2(5) NULL ,
    HST_YMD              DATE NULL 
);

ALTER TABLE TB_RCPER_LVLH_GRD_HST
    ADD CONSTRAINT  PK_TB_RCPER_LVLH_GRD_HST PRIMARY KEY (HST_NO);


ALTER TABLE TB_ABSTRCT_ADDR
    ADD (CONSTRAINT FK_ABSTRCT_ADDR_SUFRER_NO FOREIGN KEY (SUFRER_NO) REFERENCES TB_IDNTFC (SUFRER_NO) ON DELETE SET NULL);

ALTER TABLE TB_RCPER_LVLH_GRD
    ADD (CONSTRAINT FK_RCPER_LVLH_GRD_BIZ_AREA_CD FOREIGN KEY (BIZ_AREA_CD, BIZ_ODER, EXMN_ODER, APLY_NO) REFERENCES TB_MNSVY (BIZ_AREA_CD, BIZ_ODER, EXMN_ODER, APLY_NO));


COMMENT ON TABLE TB_ABSTRCT_ADDR IS '초본주소관리';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.SN IS '일련번호';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.SUFRER_NO IS '피해자번호';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.ABSTRCT_ADDR IS '초본주소';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.DCLR_YR IS '신고연도';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.DCLR_RESN IS '신고사유';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.GAP_DSTNC IS '이격거리';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.LAT IS '위도';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.LOT IS '경도';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_ABSTRCT_ADDR.MDFCN_YMD IS '수정일자';
      
   
COMMENT ON TABLE TB_DMGE_GRD_MNG IS '피해등급관리';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.DMGE_GRD_YR IS '피해등급연';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.DMGE_GRD_CD IS '피해등급코드';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.CRTR_INCOME_AMT IS '기준소득금액';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.SVRTY_BGNG_SCRE IS '중증도시작점수';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.SVRTY_END_SCRE IS '중증도종료점수';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.GRD_RATE IS '등급비율';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.GRD_AMT IS '등급금액';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_DMGE_GRD_MNG.MDFCN_YMD IS '수정일자';
      
     
COMMENT ON TABLE TB_RCPER_LVLH_GRD IS '요양생활수당평가등급';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.BIZ_AREA_CD IS '사업지역코드';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.BIZ_ODER IS '사업차수';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.EXMN_ODER IS '조사차수';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.APLY_NO IS '신청번호';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.DISS_KND_CD IS '질환종류코드';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.SVRTY_SCRE IS '중증도점수';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_RCPER_LVLH_GRD_HST IS '요양생활수당평가등급이력';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.HST_NO IS '이력번호';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.BIZ_AREA_CD IS '사업지역코드';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.BIZ_ODER IS '사업차수';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.EXMN_ODER IS '조사차수';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.APLY_NO IS '신청번호';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.DISS_KND_CD IS '질환종류코드';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.SVRTY_SCRE IS '중증도점수';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.MDFCN_YMD IS '수정일자';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.LOG_TY IS 'LOG유형';
   COMMENT ON COLUMN TB_RCPER_LVLH_GRD_HST.HST_YMD IS '이력일자';
   
*/