/**
 *  2023/02/15 운영서버 반영 완료
 */
/*
-- 2023/02/07 공휴일관리 
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_MNG1001', '공휴일관리', '/sys/hldy/listHldy.do', 'url', 'MU_ADM_MNG1000', 0, 'ADM','Y','100000', SYSDATE);
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('100000', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_MNG1001');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('100000', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_MNG1001');
*/

/**
 *  2023/02/01 운영서버 반영 완료
 */
/*
-- =============================================================================
-- 2022.12.08 피해등급관리 메뉴/프로그램/권한 등록
-- =============================================================================
/*
INSERT INTO SYS_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_LVL, MENU_ORDR, TRGT_URL, POPUP_YN, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('MU_ADM_MNG0410','MU_ADM_MNG','피해등급관리', 2, 4, '/adm/exmn/listDmgeGrd.do', 'N', 'ADM', 'Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'MU_ADM_MNG0410');
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'MU_ADM_MNG0410');
*/

INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_MNG0410', '운영관리 피해등급관리', '/adm/exmn/listDmgeGrd.do', 'url', 'MU_ADM_MNG0410', 0, 'ADM','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_MNG0411', '운영관리 피해등급관리 목록 조회', '/adm/exmn/getListDmgeGrd.do', 'url', NULL, 0, 'ADM','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_MNG0412', '운영관리 피해등급관리 상세 조회', '/adm/exmn/getDmgeGrd.do', 'url', NULL, 0, 'ADM','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_MNG0413', '운영관리 피해등급관리 저장 처리', '/adm/exmn/saveDmgeGrd.do', 'url', NULL, 0, 'ADM','Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_MNG0410');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_MNG0411');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_MNG0412');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_MNG0413');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_MNG0410');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_MNG0411');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_MNG0412');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_MNG0413');
-- 2022.12.08 17:30 RELIEF03 커밋완료

-- =============================================================================
-- 2022.12.09 본조사 - 의료비 - 세부 의료비 내역 팝업 프로그램/권한 등록
-- =============================================================================
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_EXM0222', '환경오염피해 본조사 본조사관리 세부의료비내역 조회팝업', '/adm/exmn/modalMcpSckwnd.do', 'url', NULL, 0, 'ADM','Y','system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_MNG0223', '환경오염피해 본조사 본조사관리 세부의료비내역 목록조회', '/adm/exmn/getListMcpSckwnd.do', 'url', NULL, 0, 'ADM','Y','system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_MNG0224', '환경오염피해 본조사 본조사관리 세부의료비내역 엑셀 다운로드', '/adm/exmn/downMcpSckwndExcel.do', 'url', NULL, 0, 'ADM','Y','system', SYSDATE);
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_EXM0222');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_MNG0223');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_MNG0224');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_EXM0222');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_MNG0223');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_MNG0224');
-- 2022.12.09 17:30 RELIEF03 커밋완료

-- =============================================================================
-- 2022.12.26 [구제급여 지급] 대메뉴 생성 및 요양생활수당/장의비/유족보상비 메뉴 추가
-- =============================================================================
/*
INSERT INTO SYS_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_LVL, MENU_ORDR, TRGT_URL, POPUP_YN, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('MU_ADM_RFG','NONE','구제급여 지급', 1, 1, '/adm/relief/listReliefGive.do', 'N', 'ADM', 'Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'MU_ADM_RFG');
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'MU_ADM_RFG');
-- 대메뉴 명칭 변경 / 순서 변경
UPDATE SYS_MENU SET MENU_ORDR = 0, MENU_NM = '구제급여 신청/접수' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_RLF';
UPDATE SYS_MENU SET MENU_ORDR = 1, MENU_NM = '구제급여 지급' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_RFG';
UPDATE SYS_MENU SET MENU_ORDR = 2, MENU_NM = '환경오염 피해조사' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_EXM';
UPDATE SYS_MENU SET MENU_ORDR = 3, MENU_NM = '취약계층 소송지원' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_SPT';
UPDATE SYS_MENU SET MENU_ORDR = 4, MENU_NM = 'GIS 분석' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_GIS';
UPDATE SYS_MENU SET MENU_ORDR = 5, MENU_NM = '통계 관리' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_STS';
UPDATE SYS_MENU SET MENU_ORDR = 6, MENU_NM = '운영 관리' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_MNG';
UPDATE SYS_MENU SET MENU_ORDR = 7, MENU_NM = '사용자 관리' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_USR';
UPDATE SYS_MENU SET MENU_ORDR = 8, MENU_NM = '시스템 관리' WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_SYS';
-- [구제급여 지급] 메뉴의 대메뉴 이동
UPDATE SYS_MENU SET UP_MENU_ID = 'MU_ADM_RFG', MENU_ORDR = 0, MENU_NM = '의료급여' WHERE UP_MENU_ID = 'MU_ADM_RLF' AND MENU_ID = 'MU_ADM_RLF0400';
-- [사후관리] 메뉴의 대메뉴 이동
UPDATE SYS_MENU SET UP_MENU_ID = 'MU_ADM_RFG', MENU_ORDR = 4, MENU_NM = '사후관리(구상권)' WHERE UP_MENU_ID = 'MU_ADM_RLF' AND MENU_ID = 'MU_ADM_RLF0500';
-- 메뉴 추가 및 권한 등록
INSERT INTO SYS_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_LVL, MENU_ORDR, TRGT_URL, POPUP_YN, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('MU_ADM_RFG0200','MU_ADM_RFG','요양생활수당', 2, 1, '/adm/exmn/listRcperLvlh.do', 'N', 'ADM', 'Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'MU_ADM_RFG0200');
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'MU_ADM_RFG0200');
INSERT INTO SYS_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_LVL, MENU_ORDR, TRGT_URL, POPUP_YN, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('MU_ADM_RFG0300','MU_ADM_RFG','장의비', 2, 2, '/adm/exmn/listFnrlCst.do', 'N', 'ADM', 'Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'MU_ADM_RFG0300');
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'MU_ADM_RFG0300');
INSERT INTO SYS_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_LVL, MENU_ORDR, TRGT_URL, POPUP_YN, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('MU_ADM_RFG0400','MU_ADM_RFG','유족보상비', 2, 3, '/adm/exmn/listBrvfmRwrd.do', 'N', 'ADM', 'Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'MU_ADM_RFG0400');
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'MU_ADM_RFG0400');
*/

INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_RFG0210', '구제급여지급 요양생활수당', '/adm/exmn/listRcperLvlh.do', 'url', 'MU_ADM_RFG0200', 0, 'ADM','Y', 'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_RFG0310', '구제급여지급 장의비', '/adm/exmn/listFnrlCst.do', 'url', 'MU_ADM_RFG0300', 0, 'ADM','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_RFG0410', '구제급여지급 유족보상비', '/adm/exmn/listBrvfmRwrd.do', 'url', 'MU_ADM_RFG0400', 0, 'ADM','Y',	'system', SYSDATE);
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_RFG0210');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_RFG0310');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_RFG0410');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_RFG0210');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_RFG0310');
-- 2022.12.26 10:30 RELIEF03 커밋완료

-- =============================================================================
-- 2023.01.09 [위원회 관리] 대메뉴 및 하위 메뉴 생성
-- =============================================================================
/*
-- [위원회 관리] 대메뉴 생성 및 권한 등록
INSERT INTO SYS_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_LVL, MENU_ORDR, TRGT_URL, POPUP_YN, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('MU_ADM_CMT','NONE','위원회 관리', 1, 1, '/adm/cmit/listMfcmm.do', 'N', 'ADM', 'Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'MU_ADM_CMT');
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'MU_ADM_CMT');
-- [위원 관리] 서브메뉴 생성 및 권한 등록
INSERT INTO SYS_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_LVL, MENU_ORDR, TRGT_URL, POPUP_YN, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('MU_ADM_CMT0100','MU_ADM_CMT','위원 관리', 2, 1, '/adm/cmit/listMfcmm.do', 'N', 'ADM', 'Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'MU_ADM_CMT0100');
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'MU_ADM_CMT0100');
-- [위원회 조사관리] 서브메뉴 생성 및 권한 등록
INSERT INTO SYS_MENU (MENU_ID, UP_MENU_ID, MENU_NM, MENU_LVL, MENU_ORDR, TRGT_URL, POPUP_YN, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('MU_ADM_CMT0200','MU_ADM_CMT','위원회 조사관리', 2, 2, '/adm/cmit/listCmitMng.do', 'N', 'ADM', 'Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'MU_ADM_CMT0200');
INSERT INTO SYS_ROLE_MENU (RGTR_NO, REG_YMD, ROLE_ID, MENU_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'MU_ADM_CMT0200');
-- 대메뉴 순서 변경
UPDATE SYS_MENU SET MENU_ORDR = 0 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_RLF'; -- 구제급여 신청/접수
UPDATE SYS_MENU SET MENU_ORDR = 1 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_RFG'; -- 구제급여 지급
UPDATE SYS_MENU SET MENU_ORDR = 2 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_EXM'; -- 환경오염 피해조사
UPDATE SYS_MENU SET MENU_ORDR = 3 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_SPT'; -- 취약계층 소송지원
UPDATE SYS_MENU SET MENU_ORDR = 4 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_GIS'; -- GIS 분석
UPDATE SYS_MENU SET MENU_ORDR = 5 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_CMT'; -- 위원회 관리
UPDATE SYS_MENU SET MENU_ORDR = 6 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_STS'; -- 통계 관리
UPDATE SYS_MENU SET MENU_ORDR = 7 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_MNG'; -- 운영 관리
UPDATE SYS_MENU SET MENU_ORDR = 8 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_USR'; -- 사용자 관리
UPDATE SYS_MENU SET MENU_ORDR = 9 WHERE UP_MENU_ID = 'NONE' AND MENU_ID = 'MU_ADM_SYS'; -- 시스템 관리
*/

-- 프로그램 추가 및 권한 등록
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_CMT0110', '위원회관리 위원 관리', '/adm/cmit/listMfcmm.do', 'url', 'MU_ADM_CMT0100', 0, 'ADM','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_ADM_CMT0210', '위원회관리 위원회 조사관리', '/adm/cmit/listCmitMng.do', 'url', 'MU_ADM_CMT0200', 0, 'ADM','Y', 'system', SYSDATE);
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_CMT0110');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_CMT0210');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_CMT0110');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_CMT0210');
-- 2023.01.09 10:55 RELIEF03 커밋완료

-- 2023.01.16 살생물제품 피해구제 관련 메뉴와 프로그램 추가
/*
UPDATE SYS_MENU SET TRGT_URL = '/usr/relief/openBioRelief.do' WHERE MENU_ID = 'MU_USR_RQT0400';
*/
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_USR_RQT0401', '살생물제품 구제급여 신청 방법 선택 화면', '/usr/relief/openBioRelief.do', 'url', 'MU_USR_RQT0400', 0, 'USR','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_USR_RQT0402', '살생물제품 구제급여 신청 피해자 본인 신청 화면', '/usr/relief/openBioReliefForm.do', 'url', 'MU_USR_RQT0400', 0, 'USR','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_USR_RQT0403', '살생물제품 구제급여 신청 피해자 본인 정보 조회', '/usr/relief/getBioRelief.do', 'url', 'MU_USR_RQT0400', 0, 'USR','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_USR_RQT0404', '살생물제품 구제급여 신청 피해자 본인 신청 화면 임시저장', '/usr/relief/saveBioRelief.do', 'url', 'MU_USR_RQT0400', 0, 'USR','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_USR_RQT0405', '살생물제품 구제급여 신청 피해자 본인 신청 화면 제출하기', '/usr/relief/saveBioRelief.do', 'url', 'MU_USR_RQT0400', 0, 'USR','Y',	'system', SYSDATE);
INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD) VALUES
('PG_USR_RQT0406', '살생물제품 구제급여 신청 피해자 본인 신청 파일첨부', '/usr/file/uploadBioAplyFile.do', 'url', 'MU_USR_RQT0400', 0, 'USR','Y',	'system', SYSDATE);
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_USR_RQT0401');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_USR_RQT0401');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_USR', 'PG_USR_RQT0401');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_USR_RQT0402');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_USR_RQT0402');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_USR', 'PG_USR_RQT0402');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_USR_RQT0403');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_USR_RQT0403');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_USR', 'PG_USR_RQT0403');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_USR_RQT0404');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_USR_RQT0404');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_USR', 'PG_USR_RQT0404');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_USR_RQT0405');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_USR_RQT0405');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_USR', 'PG_USR_RQT0405');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_USR_RQT0406');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_USR_RQT0406');
INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) VALUES ('system', SYSDATE, 'ROLE_AUTH_USR', 'PG_USR_RQT0406');

-- 2023.01.16 살생물제품 피해구제 관련 메뉴와 프로그램 추가


/**
 * 초본주소 & GIS 분석 프로그램 추가 (원혁)
 */
insert into SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD, MDFR_NO, MDFCN_YMD)
values ('PG_ADM_GIS0101', '초본 주소 등록', '/adm/gis/listAbstrctAddr.do', 'url', 'MU_ADM_GIS0100', 0, 'ADM', 'Y', 'system', sysdate, null, null),
    ('PG_ADM_GIS0201', 'GIS 환경 오염 영향분석', '/adm/gis/viewEvnpAffc.do', 'url', 'MU_ADM_GIS0200', 0, 'ADM', 'Y', 'system', sysdate, null, null);

-- 프로그램 권한 추가
insert into SYS_ROLE_PROG (ROLE_ID, PROG_ID, RGTR_NO, REG_YMD, MDFR_NO, MDFCN_YMD)
values ('ROLE_AUTH_SYS', 'PG_ADM_GIS0101', 'system', sysdate, null, null),
       ('ROLE_AUTH_SYS', 'PG_ADM_GIS0201', 'system', sysdate, null, null),
       ('ROLE_AUTH_ADM', 'PG_ADM_GIS0101', 'system', sysdate, null, null),
       ('ROLE_AUTH_ADM', 'PG_ADM_GIS0201', 'system', sysdate, null, null);

-- 2023.01.25 관리자시스템 살생물제품 피해구제 관련 메뉴와 프로그램 추가
UPDATE SYS_MENU SET TRGT_URL = '/adm/bio/listBioReliefRcpt.do' WHERE MENU_ID = 'MU_ADM_BIO'; -- 살생물제품 피해구제
UPDATE SYS_MENU SET TRGT_URL = '/adm/bio/listBioReliefRcpt.do' WHERE MENU_ID = 'MU_ADM_BIO0100'; -- 구제급여 접수
UPDATE SYS_MENU SET TRGT_URL = '/adm/bio/listBioMfcmm.do'      WHERE MENU_ID = 'MU_ADM_BIO0200'; -- 위원관리
UPDATE SYS_MENU SET TRGT_URL = '/adm/bio/listBioCmitMng.do'    WHERE MENU_ID = 'MU_ADM_BIO0300'; -- 위원회관리

INSERT INTO SYS_PROG (PROG_ID, PROG_NM, PROG_URL, PROG_TY, MENU_ID, PROG_ORDR, SYS_SE_CD, USE_YN, RGTR_NO, REG_YMD)
VALUES ('PG_ADM_BIO0101','살생물제품 피해구제 구제급여 접수',					'/adm/bio/listBioReliefRcpt.do', 		'url', 'MU_ADM_BIO0100', 0, 'ADM', 'Y', 'system', SYSDATE)
     , ('PG_ADM_BIO0102','살생물제품 피해구제 구제급여 접수 목록 조회',			'/adm/bio/getListBioRelief.do', 		'url', 'MU_ADM_BIO0100', 0, 'ADM', 'Y', 'system', SYSDATE)
     , ('PG_ADM_BIO0103','살생물제품 피해구제 구제급여 접수 상세 조회',			'/adm/bio/getBioRelief.do', 			'url', 'MU_ADM_BIO0100', 0, 'ADM', 'Y', 'system', SYSDATE)
     , ('PG_ADM_BIO0104','살생물제품 피해구제 구제급여 접수 제출서류 목록 조회','/adm/bio/getListBioAplySubmitFile.do', 'url', 'MU_ADM_BIO0100', 0, 'ADM', 'Y', 'system', SYSDATE)
     , ('PG_ADM_BIO0105','살생물제품 피해구제 구제급여 접수 이력관리 목록 조회','/adm/bio/getListBioMngHst.do', 		'url', 'MU_ADM_BIO0100', 0, 'ADM', 'Y', 'system', SYSDATE)
     , ('PG_ADM_BIO0106','살생물제품 피해구제 구제급여 접수 엑셀 다운로드',		'/adm/bio/downBioReliefExcel.do', 		'url', 'MU_ADM_BIO0100', 0, 'ADM', 'Y', 'system', SYSDATE)
     , ('PG_ADM_BIO0107','살생물제품 피해구제 구제급여 접수 신청서 접수 처리',	'/adm/bio/saveBioReceipt.do', 			'url', 'MU_ADM_BIO0100', 0, 'ADM', 'Y', 'system', SYSDATE)
     , ('PG_ADM_BIO0201','살생물제품 피해구제 위원 관리',						'/adm/bio/listBioMfcmm.do', 			'url', 'MU_ADM_BIO0200', 0, 'ADM', 'Y',	'system', SYSDATE)
     , ('PG_ADM_BIO0301','살생물제품 피해구제 위원회 관리',						'/adm/bio/listBioCmitMng.do', 			'url', 'MU_ADM_BIO0300', 0, 'ADM', 'Y',	'system', SYSDATE)
;

INSERT INTO SYS_ROLE_PROG (RGTR_NO, REG_YMD, ROLE_ID, PROG_ID) 
VALUES ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0101')
     , ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0102')
     , ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0103')
     , ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0104')
     , ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0105')
     , ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0106')
     , ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0107')
     , ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0201')
     , ('system', SYSDATE, 'ROLE_AUTH_SYS', 'PG_ADM_BIO0301')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0101')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0102')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0103')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0104')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0105')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0106')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0107')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0201')
     , ('system', SYSDATE, 'ROLE_AUTH_ADM', 'PG_ADM_BIO0301')
;
*/