ALTER TABLE TB_RELIEF ADD INDV_INFO_CLCT_AGRE_YN CHAR(1);
ALTER TABLE TB_RELIEF_HST ADD INDV_INFO_CLCT_AGRE_YN CHAR(1);

COMMENT ON COLUMN TB_RELIEF.INDV_INFO_CLCT_AGRE_YN IS '개인정보수집동의여부';
COMMENT ON COLUMN TB_RELIEF_HST.INDV_INFO_CLCT_AGRE_YN IS '개인정보수집동의여부';

/*
 * 컬럼 추가  
 */
/* [운영서버 반영 완료] - 2022/12/07 
-- 구제급여신청
ALTER TABLE TB_RELIEF ADD MNGR_REG_YN CHAR(1);
ALTER TABLE TB_RELIEF_HST ADD MNGR_REG_YN CHAR(1);

COMMENT ON COLUMN TB_RELIEF.MNGR_REG_YN IS '관리자등록여부';
COMMENT ON COLUMN TB_RELIEF_HST.MNGR_REG_YN IS '관리자등록여부';

-- 구제급여신청파일
ALTER TABLE TB_APLY_FILE ADD MNGR_REG_YN CHAR(1);

COMMENT ON COLUMN TB_APLY_FILE.MNGR_REG_YN IS '관리자등록여부';
*/


/**
 *  2023/02/01 운영서버 반영 완료
 */
/*
-- 구제급여신청 (12/16)
ALTER TABLE TB_RELIEF ADD DTH_YMD VARCHAR2(8);
ALTER TABLE TB_RELIEF_HST ADD DTH_YMD VARCHAR2(8);

COMMENT ON COLUMN TB_RELIEF.DTH_YMD IS '사망일자';
COMMENT ON COLUMN TB_RELIEF_HST.DTH_YMD IS '사망일자';

	-- (23/1/21)
	ALTER TABLE TB_RELIEF ADD SYS_SE_CD VARCHAR2(3);
	ALTER TABLE TB_RELIEF_HST ADD SYS_SE_CD VARCHAR2(3);
	
	COMMENT ON COLUMN TB_RELIEF.SYS_SE_CD IS '시스템구분코드';
	COMMENT ON COLUMN TB_RELIEF_HST.SYS_SE_CD IS '시스템구분코드';

	
-- 게시판
ALTER TABLE TB_BBS ADD POPUP_YN CHAR(1);
ALTER TABLE TB_BBS ADD POPUP_HGHT NUMBER(10);
ALTER TABLE TB_BBS ADD POPUP_SQR  NUMBER(10);

COMMENT ON COLUMN TB_BBS.POPUP_YN IS '팝업여부';
COMMENT ON COLUMN TB_BBS.POPUP_HGHT IS '팝업높이';
COMMENT ON COLUMN TB_BBS.POPUP_SQR IS '팝업넓이';


-- 본조사 
ALTER TABLE TB_MNSVY ADD LAST_DMGE_SCRE NUMBER(5,2);
ALTER TABLE TB_MNSVY ADD FNRL_CRTR_YR CHAR(4);
ALTER TABLE TB_MNSVY ADD FNRL_CST_GIVE_YMD VARCHAR2(8);
ALTER TABLE TB_MNSVY ADD BRVFM_RWRD_CRTR_YR CHAR(4);
ALTER TABLE TB_MNSVY ADD BRVFM_RWMNY_GIVE_YMD VARCHAR2(8);
ALTER TABLE TB_MNSVY ADD BRVFM_RWMNY_GIVE_YMD VARCHAR2(8);
ALTER TABLE TB_MNSVY ADD DMGE_GRD_YR CHAR(4);

ALTER TABLE TB_MNSVY_HST ADD LAST_DMGE_SCRE NUMBER(5,2);
ALTER TABLE TB_MNSVY_HST ADD FNRL_CRTR_YR CHAR(4);
ALTER TABLE TB_MNSVY_HST ADD FNRL_CST_GIVE_YMD VARCHAR2(8);
ALTER TABLE TB_MNSVY_HST ADD BRVFM_RWRD_CRTR_YR CHAR(4);
ALTER TABLE TB_MNSVY_HST ADD BRVFM_RWMNY_GIVE_YMD VARCHAR2(8);
ALTER TABLE TB_MNSVY_HST ADD DMGE_GRD_YR CHAR(4);

COMMENT ON COLUMN TB_MNSVY.LAST_DMGE_SCRE IS '최종피해점수';
COMMENT ON COLUMN TB_MNSVY.FNRL_CRTR_YR IS '장례기준연도';
COMMENT ON COLUMN TB_MNSVY.FNRL_CST_GIVE_YMD IS '장례비지급일자';
COMMENT ON COLUMN TB_MNSVY.BRVFM_RWRD_CRTR_YR IS '유족보상기준연도';
COMMENT ON COLUMN TB_MNSVY.BRVFM_RWMNY_GIVE_YMD IS '유족보상금지급일자';
COMMENT ON COLUMN TB_MNSVY.DMGE_GRD_YR IS '피해등급연도';

COMMENT ON COLUMN TB_MNSVY_HST.LAST_DMGE_SCRE IS '최종피해점수';
COMMENT ON COLUMN TB_MNSVY_HST.FNRL_CRTR_YR IS '장례기준연도';
COMMENT ON COLUMN TB_MNSVY_HST.FNRL_CST_GIVE_YMD IS '장례비지급일자';
COMMENT ON COLUMN TB_MNSVY_HST.BRVFM_RWRD_CRTR_YR IS '유족보상기준연도';
COMMENT ON COLUMN TB_MNSVY_HST.BRVFM_RWMNY_GIVE_YMD IS '유족보상금지급일자';
COMMENT ON COLUMN TB_MNSVY_HST.DMGE_GRD_YR IS '피해등급연도';


-- 요양생활수당 (지급금액)
ALTER TABLE TB_RCPER_LVLH_DTLS          ADD GIVE_AMT NUMBER(15);
ALTER TABLE TB_RCPER_LVLH_DTLS          ADD GIVE_SE_CD VARCHAR2(2);
ALTER TABLE TB_RCPER_LVLH_DTLS_HST      ADD GIVE_AMT NUMBER(15);
ALTER TABLE TB_RCPER_LVLH_DTLS_HST      ADD GIVE_SE_CD VARCHAR2(2);
    
COMMENT ON COLUMN TB_RCPER_LVLH_DTLS.GIVE_AMT IS '지급금액';
COMMENT ON COLUMN TB_RCPER_LVLH_DTLS.GIVE_SE_CD IS '지급구분코드';
COMMENT ON COLUMN TB_RCPER_LVLH_DTLS_HST.GIVE_AMT IS '지급금액';
COMMENT ON COLUMN TB_RCPER_LVLH_DTLS_HST.GIVE_SE_CD IS '지급구분코드';


-- 피해자정보 (거주기간)
ALTER TABLE TB_IDNTFC       ADD RESI_WHL_CN VARCHAR2(300);
ALTER TABLE TB_IDNTFC_HST   ADD RESI_WHL_CN VARCHAR2(300);

COMMENT ON COLUMN TB_IDNTFC.RESI_WHL_CN IS '거주기간내용';
COMMENT ON COLUMN TB_IDNTFC_HST.RESI_WHL_CN IS '거주기간내용';


-- 사업차수
ALTER TABLE TB_BIZ_ODER     ADD FRST_POLLUTN_OCRN_YR CHAR(4);
ALTER TABLE TB_BIZ_ODER     ADD LAST_POLLUTN_OCRN_YR CHAR(4);
ALTER TABLE TB_BIZ_ODER     ADD AFFC_SCOPE_DSTNC NUMBER(10,3);

COMMENT ON COLUMN TB_BIZ_ODER.FRST_POLLUTN_OCRN_YR IS '최초오염발생연도';
COMMENT ON COLUMN TB_BIZ_ODER.LAST_POLLUTN_OCRN_YR IS '최종오염발생연도';
COMMENT ON COLUMN TB_BIZ_ODER.AFFC_SCOPE_DSTNC IS '영향범위거리';


-- 이력관리 (관계KEY번호)
ALTER TABLE TB_MNG_HST       ADD REL_KEY_NO NUMBER(10);

COMMENT ON COLUMN TB_MNG_HST.REL_KEY_NO IS '관계KEY번호';

    
-- 사업관리 (위도, 경도)
ALTER TABLE TB_BIZ_MNG     ADD LAT NUMBER(12,10);
ALTER TABLE TB_BIZ_MNG     ADD LOT NUMBER(13,10);

COMMENT ON COLUMN TB_BIZ_MNG.LAT IS '위도';
COMMENT ON COLUMN TB_BIZ_MNG.LOT IS '경도';
*/