/**
 *  2023/02/01 운영서버 반영 완료
 */
/*
DROP TABLE TB_CMIT_MNG CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_MFCMM_TENURE CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_MFCMM CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_CMIT_DMGE CASCADE CONSTRAINTS PURGE;

CREATE TABLE TB_CMIT_DMGE
(
    CMIT_MNG_NO          NUMBER(10) NOT NULL ,
    BIZ_AREA_CD          VARCHAR2(10) NULL ,
    DMGE_SE_CD           VARCHAR2(2) NULL ,
    CMIT_SE_CD           VARCHAR2(2) NULL ,
    EXMN_SE_CD           VARCHAR2(2) NULL ,
    CMIT_ODER            VARCHAR2(20) NULL ,
    CMIT_NM              VARCHAR2(100) NULL ,
    OPMT_BGNG_YMD        VARCHAR2(8) NULL ,
    OPMT_END_YMD         VARCHAR2(8) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_CMIT_DMGE
    ADD CONSTRAINT  PK_TB_CMIT_DMGE PRIMARY KEY (CMIT_MNG_NO);

CREATE TABLE TB_CMIT_MNG
(
    CMIT_MNG_NO          NUMBER(10) NOT NULL ,
    TENURE_NO            NUMBER(10) NOT NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL 
);

ALTER TABLE TB_CMIT_MNG
    ADD CONSTRAINT  PK_TB_CMIT_MNG PRIMARY KEY (CMIT_MNG_NO,TENURE_NO);

CREATE TABLE TB_MFCMM
(
    MFCMM_NO             NUMBER(10) NOT NULL ,
    MFCMM_NM             VARCHAR2(40) NULL ,
    MFCMM_OGDP_NM        VARCHAR2(100) NULL ,
    MFCMM_RLM_CD         VARCHAR2(5) NULL ,
    MFCMM_RSPOFC_NM      VARCHAR2(100) NULL ,
    MFCMM_TELNO          VARCHAR2(11) NULL ,
    MFCMM_BRDT           CHAR(8) NULL ,
    MFCMM_EML_ADDR       VARCHAR2(100) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_MFCMM
    ADD CONSTRAINT  PK_TB_MFCMM PRIMARY KEY (MFCMM_NO);

CREATE TABLE TB_MFCMM_TENURE
(
    TENURE_NO            NUMBER(10) NOT NULL ,
    MFCMM_NO             NUMBER(10) NULL ,
    CMIT_SE_CD           VARCHAR2(2) NULL ,
    BIZ_AREA_CD          VARCHAR2(10) NULL ,
    TENURE_ODER          VARCHAR2(20) NULL ,
    TENURE_BGNG_YMD      VARCHAR2(8) NULL ,
    TENURE_END_YMD       VARCHAR2(8) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_MFCMM_TENURE
    ADD CONSTRAINT  PK_TB_MFCMM_TENURE PRIMARY KEY (TENURE_NO);

ALTER TABLE TB_CMIT_MNG
    ADD (CONSTRAINT FK_CMIT_MNG_CMIT_MNG_NO FOREIGN KEY (CMIT_MNG_NO) REFERENCES TB_CMIT_DMGE (CMIT_MNG_NO));

ALTER TABLE TB_CMIT_MNG
    ADD (CONSTRAINT FK_CMIT_MNG_TENURE_NO FOREIGN KEY (TENURE_NO) REFERENCES TB_MFCMM_TENURE (TENURE_NO));

ALTER TABLE TB_MFCMM_TENURE
    ADD (CONSTRAINT FK_MFCMM_TENURE_MFCMM_NO FOREIGN KEY (MFCMM_NO) REFERENCES TB_MFCMM (MFCMM_NO) ON DELETE SET NULL);

COMMENT ON TABLE TB_CMIT_DMGE IS '위원회피해조사';
   COMMENT ON COLUMN TB_CMIT_DMGE.CMIT_MNG_NO IS '위원회관리번호';
   COMMENT ON COLUMN TB_CMIT_DMGE.BIZ_AREA_CD IS '사업지역코드';
   COMMENT ON COLUMN TB_CMIT_DMGE.DMGE_SE_CD IS '피해구분코드';
   COMMENT ON COLUMN TB_CMIT_DMGE.CMIT_SE_CD IS '위원회구분코드';
   COMMENT ON COLUMN TB_CMIT_DMGE.EXMN_SE_CD IS '조사구분코드';
   COMMENT ON COLUMN TB_CMIT_DMGE.CMIT_ODER IS '위원회차수';
   COMMENT ON COLUMN TB_CMIT_DMGE.CMIT_NM IS '위원회명';
   COMMENT ON COLUMN TB_CMIT_DMGE.OPMT_BGNG_YMD IS '개최시작일자';
   COMMENT ON COLUMN TB_CMIT_DMGE.OPMT_END_YMD IS '개최종료일자';
   COMMENT ON COLUMN TB_CMIT_DMGE.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_CMIT_DMGE.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_CMIT_DMGE.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_CMIT_DMGE.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_CMIT_MNG IS '위원회관리';
   COMMENT ON COLUMN TB_CMIT_MNG.CMIT_MNG_NO IS '위원회관리번호';
   COMMENT ON COLUMN TB_CMIT_MNG.TENURE_NO IS '임기번호';
   COMMENT ON COLUMN TB_CMIT_MNG.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_CMIT_MNG.REG_YMD IS '등록일자';
   
COMMENT ON TABLE TB_MFCMM IS '위원정보';
   COMMENT ON COLUMN TB_MFCMM.MFCMM_NO IS '위원번호';
   COMMENT ON COLUMN TB_MFCMM.MFCMM_NM IS '위원명';
   COMMENT ON COLUMN TB_MFCMM.MFCMM_OGDP_NM IS '위원소속명';
   COMMENT ON COLUMN TB_MFCMM.MFCMM_RLM_CD IS '위원분야코드';
   COMMENT ON COLUMN TB_MFCMM.MFCMM_RSPOFC_NM IS '위원직책명';
   COMMENT ON COLUMN TB_MFCMM.MFCMM_TELNO IS '위원전화번호';
   COMMENT ON COLUMN TB_MFCMM.MFCMM_BRDT IS '위원생년월일';
   COMMENT ON COLUMN TB_MFCMM.MFCMM_EML_ADDR IS '위원이메일주소';
   COMMENT ON COLUMN TB_MFCMM.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_MFCMM.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_MFCMM.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_MFCMM.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_MFCMM_TENURE IS '위원임기차수';
   COMMENT ON COLUMN TB_MFCMM_TENURE.TENURE_NO IS '임기번호';
   COMMENT ON COLUMN TB_MFCMM_TENURE.MFCMM_NO IS '위원번호';
   COMMENT ON COLUMN TB_MFCMM_TENURE.CMIT_SE_CD IS '위원회구분코드';
   COMMENT ON COLUMN TB_MFCMM_TENURE.BIZ_AREA_CD IS '사업지역코드';
   COMMENT ON COLUMN TB_MFCMM_TENURE.TENURE_ODER IS '임기차수';
   COMMENT ON COLUMN TB_MFCMM_TENURE.TENURE_BGNG_YMD IS '임기시작일자';
   COMMENT ON COLUMN TB_MFCMM_TENURE.TENURE_END_YMD IS '임기종료일자';
   COMMENT ON COLUMN TB_MFCMM_TENURE.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_MFCMM_TENURE.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_MFCMM_TENURE.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_MFCMM_TENURE.MDFCN_YMD IS '수정일자';
*/   

