/**
 *  2023/02/01 운영서버 반영 완료
 */
/*
DROP TABLE TB_BIO_RELIEF CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_IDNTFC CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_CMIT_MNG CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_MFCMM_TENURE CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_MFCMM CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_CMIT_DMGE CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_APLY_FILE CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_MNG_HST CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_RELIEF_HST CASCADE CONSTRAINTS PURGE;

DROP TABLE TB_BIO_IDNTFC_HST CASCADE CONSTRAINTS PURGE;

CREATE TABLE TB_BIO_APLY_FILE
(
    SN                   NUMBER(10) NOT NULL ,
    DTY_SE_CD            VARCHAR2(10) NULL ,
    DCMT_NO              VARCHAR2(10) NULL ,
    DTL_DCMT_NO          NUMBER(10) NULL ,
    PAPE_CD              VARCHAR2(10) NULL ,
    FILE_PATH            VARCHAR2(200) NULL ,
    STRG_FILE_NM         VARCHAR2(200) NULL ,
    FILE_NM              VARCHAR2(200) NULL ,
    FILE_SZ              NUMBER(14) NULL ,
    PRCS_STUS_CD         VARCHAR2(2) NULL ,
    PRCS_CN              VARCHAR2(2000) NULL ,
    DEL_YN               CHAR(1) NULL ,
    MNGR_REG_YN          CHAR(1) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_BIO_APLY_FILE
    ADD CONSTRAINT  PK_TB_BIO_APLY_FILE PRIMARY KEY (SN);

CREATE TABLE TB_BIO_CMIT_DMGE
(
    CMIT_MNG_NO          NUMBER(10) NOT NULL ,
    BIZ_AREA_CD          VARCHAR2(10) NULL ,
    DMGE_SE_CD           VARCHAR2(2) NULL ,
    CMIT_SE_CD           VARCHAR2(2) NULL ,
    EXMN_SE_CD           VARCHAR2(2) NULL ,
    CMIT_ODER            VARCHAR2(10) NULL ,
    CMIT_NM              VARCHAR2(100) NULL ,
    OPMT_BGNG_YMD        VARCHAR2(8) NULL ,
    OPMT_END_YMD         VARCHAR2(8) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_BIO_CMIT_DMGE
    ADD CONSTRAINT  PK_TB_BIO_CMIT_DMGE PRIMARY KEY (CMIT_MNG_NO);

CREATE TABLE TB_BIO_CMIT_MNG
(
    CMIT_MNG_NO          NUMBER(10) NOT NULL ,
    TENURE_NO            NUMBER(10) NOT NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL 
);

ALTER TABLE TB_BIO_CMIT_MNG
    ADD CONSTRAINT  PK_TB_BIO_CMIT_MNG PRIMARY KEY (CMIT_MNG_NO,TENURE_NO);

CREATE TABLE TB_BIO_IDNTFC
(
    SUFRER_NO            NUMBER(10) NOT NULL ,
    IDNTFC_ID            VARCHAR2(20) NULL ,
    SUFRER_NM            VARCHAR2(40) NULL ,
    SUFRER_BRDT          CHAR(8) NULL ,
    SUFRER_RRNO          VARCHAR2(80) NULL ,
    SUFRER_SXDST         CHAR(1) NULL ,
    SUFRER_ZIP           CHAR(5) NULL ,
    SUFRER_ADDR          VARCHAR2(200) NULL ,
    SUFRER_DADDR         VARCHAR2(200) NULL ,
    SUFRER_EML_ADDR      VARCHAR2(100) NULL ,
    SUFRER_TELNO         VARCHAR2(11) NULL ,
    SUFRER_MBTEL_NO      VARCHAR2(20) NULL ,
    SUFRER_AGE           NUMBER(3) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_BIO_IDNTFC
    ADD CONSTRAINT  PK_TB_BIO_IDNTFC PRIMARY KEY (SUFRER_NO);

CREATE TABLE TB_BIO_IDNTFC_HST
(
    HST_NO               NUMBER(10) NOT NULL ,
    SUFRER_NO            NUMBER(10) NULL ,
    IDNTFC_ID            VARCHAR2(20) NULL ,
    SUFRER_NM            VARCHAR2(40) NULL ,
    SUFRER_BRDT          CHAR(8) NULL ,
    SUFRER_RRNO          VARCHAR2(80) NULL ,
    SUFRER_SXDST         CHAR(1) NULL ,
    SUFRER_ZIP           CHAR(5) NULL ,
    SUFRER_ADDR          VARCHAR2(200) NULL ,
    SUFRER_DADDR         VARCHAR2(200) NULL ,
    SUFRER_EML_ADDR      VARCHAR2(100) NULL ,
    SUFRER_TELNO         VARCHAR2(11) NULL ,
    SUFRER_MBTEL_NO      VARCHAR2(20) NULL ,
    SUFRER_AGE           NUMBER(3) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL ,
    LOG_TY               VARCHAR2(5) NULL ,
    HST_YMD              DATE NULL 
);

ALTER TABLE TB_BIO_IDNTFC_HST
    ADD CONSTRAINT  PK_TB_BIO_IDNTFC_HST PRIMARY KEY (HST_NO);

CREATE TABLE TB_BIO_MFCMM
(
    MFCMM_NO             NUMBER(10) NOT NULL ,
    MFCMM_NM             VARCHAR2(40) NULL ,
    MFCMM_OGDP_NM        VARCHAR2(100) NULL ,
    MFCMM_RLM_CD         VARCHAR2(5) NULL ,
    MFCMM_RSPOFC_NM      VARCHAR2(100) NULL ,
    MFCMM_TELNO          VARCHAR2(11) NULL ,
    MFCMM_BRDT           CHAR(8) NULL ,
    MFCMM_EML_ADDR       VARCHAR2(100) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_BIO_MFCMM
    ADD CONSTRAINT  PK_TB_BIO_MFCMM PRIMARY KEY (MFCMM_NO);

CREATE TABLE TB_BIO_MFCMM_TENURE
(
    TENURE_NO            NUMBER(10) NOT NULL ,
    MFCMM_NO             NUMBER(10) NULL ,
    CMIT_SE_CD           VARCHAR2(2) NULL ,
    BIZ_AREA_CD          VARCHAR2(10) NULL ,
    TENURE_ODER          VARCHAR2(10) NULL ,
    TENURE_BGNG_YMD      VARCHAR2(8) NULL ,
    TENURE_END_YMD       VARCHAR2(8) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_BIO_MFCMM_TENURE
    ADD CONSTRAINT  PK_TB_BIO_MFCMM_TENURE PRIMARY KEY (TENURE_NO);

CREATE TABLE TB_BIO_MNG_HST
(
    SN                   NUMBER(10) NOT NULL ,
    DTY_SE_CD            VARCHAR2(10) NULL ,
    APLY_NO              VARCHAR2(10) NULL ,
    HST_SE_CD            VARCHAR2(10) NULL ,
    HST_CN               VARCHAR2(2000) NULL ,
    PARTCLR_MATTR_CN     VARCHAR2(2000) NULL ,
    REL_KEY_NO           NUMBER(10) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_BIO_MNG_HST
    ADD CONSTRAINT  PK_TB_BIO_MNG_HST PRIMARY KEY (SN);

CREATE TABLE TB_BIO_RELIEF
(
    APLY_NO              VARCHAR2(10) NOT NULL ,
    APLY_SE_CD           VARCHAR2(30) NULL ,
    APLY_KND_CD          VARCHAR2(30) NULL ,
    APLY_RESN            VARCHAR2(200) NULL ,
    SUFRER_NO            NUMBER(10) NULL ,
    APLCNT_NO            VARCHAR2(20) NULL ,
    APLCNT_NM            VARCHAR2(40) NULL ,
    APLCNT_BRDT          CHAR(8) NULL ,
    APLCNT_RRNO          VARCHAR2(80) NULL ,
    APLCNT_TELNO         VARCHAR2(11) NULL ,
    APLCNT_MBTEL_NO      VARCHAR2(20) NULL ,
    APLCNT_EML_ADDR      VARCHAR2(100) NULL ,
    APLCNT_ZIP           CHAR(5) NULL ,
    APLCNT_ADDR          VARCHAR2(200) NULL ,
    APLCNT_DADDR         VARCHAR2(200) NULL ,
    SUFRER_REL_CD        VARCHAR2(2) NULL ,
    DMGE_PRDUCT_CD       VARCHAR2(5) NULL ,
    DMGE_PRDUCT_CN       VARCHAR2(200) NULL ,
    PRDUCT_SBMSN_YN      CHAR(1) NULL ,
    PRDUCT_SBMSN_RESN    VARCHAR2(200) NULL ,
    PRDUCT_USE_PRPS      VARCHAR2(1000) NULL ,
    PRDUCT_USE_SE        VARCHAR2(2) NULL ,
    PRDUCT_USE_PLCE      VARCHAR2(200) NULL ,
    PRDUCT_USE_MTHD      VARCHAR2(1000) NULL ,
    PRDUCT_IDNTY_YN      CHAR(1) NULL ,
    PRDUCT_USE_BGNG_YMD  VARCHAR2(8) NULL ,
    PRDUCT_USE_END_YMD   VARCHAR2(8) NULL ,
    PRDUCT_USE_BGNG_HOUR CHAR(2) NULL ,
    PRDUCT_USE_END_HOUR  CHAR(2) NULL ,
    PRDUCT_USE_CUNT_CN   VARCHAR2(200) NULL ,
    PRDUCT_USGQTY_CN     VARCHAR2(200) NULL ,
    DMGE_DISS_NM         VARCHAR2(200) NULL ,
    ETC_OPINION_CN       VARCHAR2(1000) NULL ,
    BANK_NM              VARCHAR2(200) NULL ,
    DPSTR_NM             VARCHAR2(100) NULL ,
    ACTNO                VARCHAR2(80) NULL ,
    DTH_YN               CHAR(1) NULL ,
    DTH_YMD              VARCHAR2(8) NULL ,
    DMGE_RCOGN_YN        CHAR(1) NULL ,
    PRIORD_BRVFM_NM      VARCHAR2(40) NULL ,
    PRIORD_BRVFM_REL_CD  VARCHAR2(2) NULL ,
    ASGNR_NM             VARCHAR2(40) NULL ,
    ASGNR_REL_CD         VARCHAR2(2) NULL ,
    ABSTRCT_ZIP          CHAR(5) NULL ,
    ABSTRCT_ADDR         VARCHAR2(200) NULL ,
    ABSTRCT_DADDR        VARCHAR2(200) NULL ,
    FRST_APLY_YN         CHAR(1) NULL ,
    FRST_APLY_NO         VARCHAR2(10) NULL ,
    APLY_YMD             VARCHAR2(8) NULL ,
    RCPT_YMD             VARCHAR2(8) NULL ,
    PRGRE_STUS_CD        VARCHAR2(2) NULL ,
    SIGN_CN              VARCHAR2(300) NULL ,
    MNGR_REG_YN          CHAR(1) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL 
);

ALTER TABLE TB_BIO_RELIEF
    ADD CONSTRAINT  PK_TB_BIO_RELIEF PRIMARY KEY (APLY_NO);

CREATE TABLE TB_BIO_RELIEF_HST
(
    HST_NO               NUMBER(10) NOT NULL ,
    APLY_NO              VARCHAR2(10) NULL ,
    APLY_SE_CD           VARCHAR2(30) NULL ,
    APLY_KND_CD          VARCHAR2(30) NULL ,
    APLY_RESN            VARCHAR2(200) NULL ,
    SUFRER_NO            NUMBER(10) NULL ,
    APLCNT_NO            VARCHAR2(20) NULL ,
    APLCNT_NM            VARCHAR2(40) NULL ,
    APLCNT_BRDT          CHAR(8) NULL ,
    APLCNT_RRNO          VARCHAR2(80) NULL ,
    APLCNT_TELNO         VARCHAR2(11) NULL ,
    APLCNT_MBTEL_NO      VARCHAR2(20) NULL ,
    APLCNT_EML_ADDR      VARCHAR2(100) NULL ,
    APLCNT_ZIP           CHAR(5) NULL ,
    APLCNT_ADDR          VARCHAR2(200) NULL ,
    APLCNT_DADDR         VARCHAR2(200) NULL ,
    SUFRER_REL_CD        VARCHAR2(2) NULL ,
    DMGE_PRDUCT_CD       VARCHAR2(5) NULL ,
    DMGE_PRDUCT_CN       VARCHAR2(200) NULL ,
    PRDUCT_SBMSN_YN      CHAR(1) NULL ,
    PRDUCT_SBMSN_RESN    VARCHAR2(200) NULL ,
    PRDUCT_USE_PRPS      VARCHAR2(1000) NULL ,
    PRDUCT_USE_SE        VARCHAR2(2) NULL ,
    PRDUCT_USE_PLCE      VARCHAR2(200) NULL ,
    PRDUCT_USE_MTHD      VARCHAR2(1000) NULL ,
    PRDUCT_IDNTY_YN      CHAR(1) NULL ,
    PRDUCT_USE_BGNG_YMD  VARCHAR2(8) NULL ,
    PRDUCT_USE_END_YMD   VARCHAR2(8) NULL ,
    PRDUCT_USE_BGNG_HOUR CHAR(2) NULL ,
    PRDUCT_USE_END_HOUR  CHAR(2) NULL ,
    PRDUCT_USE_CUNT_CN   VARCHAR2(200) NULL ,
    PRDUCT_USGQTY_CN     VARCHAR2(200) NULL ,
    DMGE_DISS_NM         VARCHAR2(200) NULL ,
    ETC_OPINION_CN       VARCHAR2(1000) NULL ,
    BANK_NM              VARCHAR2(200) NULL ,
    DPSTR_NM             VARCHAR2(100) NULL ,
    ACTNO                VARCHAR2(80) NULL ,
    DTH_YN               CHAR(1) NULL ,
    DTH_YMD              VARCHAR2(8) NULL ,
    DMGE_RCOGN_YN        CHAR(1) NULL ,
    PRIORD_BRVFM_NM      VARCHAR2(40) NULL ,
    PRIORD_BRVFM_REL_CD  VARCHAR2(2) NULL ,
    ASGNR_NM             VARCHAR2(40) NULL ,
    ASGNR_REL_CD         VARCHAR2(2) NULL ,
    ABSTRCT_ZIP          CHAR(5) NULL ,
    ABSTRCT_ADDR         VARCHAR2(200) NULL ,
    ABSTRCT_DADDR        VARCHAR2(200) NULL ,
    FRST_APLY_YN         CHAR(1) NULL ,
    FRST_APLY_NO         VARCHAR2(10) NULL ,
    APLY_YMD             VARCHAR2(8) NULL ,
    RCPT_YMD             VARCHAR2(8) NULL ,
    PRGRE_STUS_CD        VARCHAR2(2) NULL ,
    SIGN_CN              VARCHAR2(300) NULL ,
    MNGR_REG_YN          CHAR(1) NULL ,
    RGTR_NO              VARCHAR2(20) NULL ,
    REG_YMD              DATE NULL ,
    MDFR_NO              VARCHAR2(20) NULL ,
    MDFCN_YMD            DATE NULL ,
    LOG_TY               VARCHAR2(5) NULL ,
    HST_YMD              DATE NULL 
);

ALTER TABLE TB_BIO_RELIEF_HST
    ADD CONSTRAINT  PK_TB_BIO_RELIEF_HST PRIMARY KEY (HST_NO);

ALTER TABLE TB_BIO_CMIT_MNG
    ADD (CONSTRAINT FK_BIO_CMIT_MNG_CMIT_MNG_NO FOREIGN KEY (CMIT_MNG_NO) REFERENCES TB_BIO_CMIT_DMGE (CMIT_MNG_NO));

ALTER TABLE TB_BIO_CMIT_MNG
    ADD (CONSTRAINT FK_BIO_CMIT_MNG_TENURE_NO FOREIGN KEY (TENURE_NO) REFERENCES TB_BIO_MFCMM_TENURE (TENURE_NO));

ALTER TABLE TB_BIO_MFCMM_TENURE
    ADD (CONSTRAINT FK_BIO_MFCMM_TENUR_MFCMM_NO FOREIGN KEY (MFCMM_NO) REFERENCES TB_BIO_MFCMM (MFCMM_NO) ON DELETE SET NULL);

ALTER TABLE TB_BIO_RELIEF
    ADD (CONSTRAINT FK_BIO_RELIEF_SUFRER_NO FOREIGN KEY (SUFRER_NO) REFERENCES TB_BIO_IDNTFC (SUFRER_NO) ON DELETE SET NULL);

COMMENT ON TABLE TB_BIO_APLY_FILE IS '살생물_신청첨부파일';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.SN IS '일련번호';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.DTY_SE_CD IS '업무구분코드';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.DCMT_NO IS '문서번호';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.DTL_DCMT_NO IS '세부문서번호';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.PAPE_CD IS '서류코드';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.FILE_PATH IS '파일경로';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.STRG_FILE_NM IS '저장파일명';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.FILE_NM IS '파일명';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.FILE_SZ IS '파일크기';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.PRCS_STUS_CD IS '처리상태코드';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.PRCS_CN IS '처리내용';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.DEL_YN IS '삭제여부';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.MNGR_REG_YN IS '관리자등록여부';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_APLY_FILE.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_BIO_CMIT_DMGE IS '살생물_위원해피해조사';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.CMIT_MNG_NO IS '위원회관리번호';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.BIZ_AREA_CD IS '사업지역코드';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.DMGE_SE_CD IS '피해구분코드';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.CMIT_SE_CD IS '위원회구분코드';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.EXMN_SE_CD IS '조사구분코드';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.CMIT_ODER IS '위원회차수';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.CMIT_NM IS '위원회명';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.OPMT_BGNG_YMD IS '개최시작일자';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.OPMT_END_YMD IS '개최종료일자';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_CMIT_DMGE.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_BIO_CMIT_MNG IS '살생물_위원회관리';
   COMMENT ON COLUMN TB_BIO_CMIT_MNG.CMIT_MNG_NO IS '위원회관리번호';
   COMMENT ON COLUMN TB_BIO_CMIT_MNG.TENURE_NO IS '임기번호';
   COMMENT ON COLUMN TB_BIO_CMIT_MNG.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_CMIT_MNG.REG_YMD IS '등록일자';
   
COMMENT ON TABLE TB_BIO_IDNTFC IS '살생물_피해자정보';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_NO IS '피해자번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC.IDNTFC_ID IS '식별ID';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_NM IS '피해자명';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_BRDT IS '피해자생년월일';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_RRNO IS '피해자주민등록번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_SXDST IS '피해자성별';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_ZIP IS '피해자우편번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_ADDR IS '피해자주소';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_DADDR IS '피해자상세주소';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_EML_ADDR IS '피해자이메일주소';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_TELNO IS '피해자전화번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_MBTEL_NO IS '피해자휴대전화번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC.SUFRER_AGE IS '피해자연령';
   COMMENT ON COLUMN TB_BIO_IDNTFC.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_IDNTFC.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_BIO_IDNTFC_HST IS '살생물_피해자정보이력';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.HST_NO IS '이력번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_NO IS '피해자번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.IDNTFC_ID IS '식별ID';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_NM IS '피해자명';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_BRDT IS '피해자생년월일';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_RRNO IS '피해자주민등록번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_SXDST IS '피해자성별';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_ZIP IS '피해자우편번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_ADDR IS '피해자주소';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_DADDR IS '피해자상세주소';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_EML_ADDR IS '피해자이메일주소';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_TELNO IS '피해자전화번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_MBTEL_NO IS '피해자휴대전화번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.SUFRER_AGE IS '피해자연령';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.MDFCN_YMD IS '수정일자';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.LOG_TY IS 'LOG유형';
   COMMENT ON COLUMN TB_BIO_IDNTFC_HST.HST_YMD IS '이력일자';
   
COMMENT ON TABLE TB_BIO_MFCMM IS '살생물_위원정보';
   COMMENT ON COLUMN TB_BIO_MFCMM.MFCMM_NO IS '위원번호';
   COMMENT ON COLUMN TB_BIO_MFCMM.MFCMM_NM IS '위원명';
   COMMENT ON COLUMN TB_BIO_MFCMM.MFCMM_OGDP_NM IS '위원소속명';
   COMMENT ON COLUMN TB_BIO_MFCMM.MFCMM_RLM_CD IS '위원분야코드';
   COMMENT ON COLUMN TB_BIO_MFCMM.MFCMM_RSPOFC_NM IS '위원직책명';
   COMMENT ON COLUMN TB_BIO_MFCMM.MFCMM_TELNO IS '위원전화번호';
   COMMENT ON COLUMN TB_BIO_MFCMM.MFCMM_BRDT IS '위원생년월일';
   COMMENT ON COLUMN TB_BIO_MFCMM.MFCMM_EML_ADDR IS '위원이메일주소';
   COMMENT ON COLUMN TB_BIO_MFCMM.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_MFCMM.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_MFCMM.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_MFCMM.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_BIO_MFCMM_TENURE IS '살생물_위원임기차수';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.TENURE_NO IS '임기번호';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.MFCMM_NO IS '위원번호';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.CMIT_SE_CD IS '위원회구분코드';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.BIZ_AREA_CD IS '사업지역코드';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.TENURE_ODER IS '임기차수';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.TENURE_BGNG_YMD IS '임기시작일자';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.TENURE_END_YMD IS '임기종료일자';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_MFCMM_TENURE.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_BIO_MNG_HST IS '살생물_관리이력정보';
   COMMENT ON COLUMN TB_BIO_MNG_HST.SN IS '일련번호';
   COMMENT ON COLUMN TB_BIO_MNG_HST.DTY_SE_CD IS '업무구분코드';
   COMMENT ON COLUMN TB_BIO_MNG_HST.APLY_NO IS '신청번호';
   COMMENT ON COLUMN TB_BIO_MNG_HST.HST_SE_CD IS '이력구분코드';
   COMMENT ON COLUMN TB_BIO_MNG_HST.HST_CN IS '이력내용';
   COMMENT ON COLUMN TB_BIO_MNG_HST.PARTCLR_MATTR_CN IS '특이사항내용';
   COMMENT ON COLUMN TB_BIO_MNG_HST.REL_KEY_NO IS '관계KEY번호';
   COMMENT ON COLUMN TB_BIO_MNG_HST.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_MNG_HST.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_MNG_HST.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_MNG_HST.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_BIO_RELIEF IS '살생물_구제급여신청';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLY_NO IS '신청번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLY_SE_CD IS '신청구분코드';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLY_KND_CD IS '신청종류코드';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLY_RESN IS '신청사유';
   COMMENT ON COLUMN TB_BIO_RELIEF.SUFRER_NO IS '피해자번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_NO IS '신청자번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_NM IS '신청자명';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_BRDT IS '신청자생년월일';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_RRNO IS '신청자주민등록번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_TELNO IS '신청자전화번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_MBTEL_NO IS '신청자휴대전화번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_EML_ADDR IS '신청자이메일주소';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_ZIP IS '신청자우편번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_ADDR IS '신청자주소';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLCNT_DADDR IS '신청자상세주소';
   COMMENT ON COLUMN TB_BIO_RELIEF.SUFRER_REL_CD IS '피해자관계코드';
   COMMENT ON COLUMN TB_BIO_RELIEF.DMGE_PRDUCT_CD IS '피해제품코드';
   COMMENT ON COLUMN TB_BIO_RELIEF.DMGE_PRDUCT_CN IS '피해제품내용';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_SBMSN_YN IS '제품제출여부';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_SBMSN_RESN IS '제품제출사유';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_PRPS IS '제품사용목적';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_SE IS '제품사용구분';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_PLCE IS '제품사용장소';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_MTHD IS '제품사용방법';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_IDNTY_YN IS '제품확인여부';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_BGNG_YMD IS '제품사용시작일자';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_END_YMD IS '제품사용종료일자';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_BGNG_HOUR IS '제품사용시작시';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_END_HOUR IS '제품사용종료시';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USE_CUNT_CN IS '제품사용횟수내용';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRDUCT_USGQTY_CN IS '제품사용량내용';
   COMMENT ON COLUMN TB_BIO_RELIEF.DMGE_DISS_NM IS '피해질환명';
   COMMENT ON COLUMN TB_BIO_RELIEF.ETC_OPINION_CN IS '기타의견내용';
   COMMENT ON COLUMN TB_BIO_RELIEF.BANK_NM IS '은행명';
   COMMENT ON COLUMN TB_BIO_RELIEF.DPSTR_NM IS '예금주명';
   COMMENT ON COLUMN TB_BIO_RELIEF.ACTNO IS '계좌번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.DTH_YN IS '사망여부';
   COMMENT ON COLUMN TB_BIO_RELIEF.DTH_YMD IS '사망일자';
   COMMENT ON COLUMN TB_BIO_RELIEF.DMGE_RCOGN_YN IS '피해인정여부';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRIORD_BRVFM_NM IS '선순위유족명';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRIORD_BRVFM_REL_CD IS '선순위유족관계코드';
   COMMENT ON COLUMN TB_BIO_RELIEF.ASGNR_NM IS '양도인명';
   COMMENT ON COLUMN TB_BIO_RELIEF.ASGNR_REL_CD IS '양도인관계코드';
   COMMENT ON COLUMN TB_BIO_RELIEF.ABSTRCT_ZIP IS '초본우편번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.ABSTRCT_ADDR IS '초본주소';
   COMMENT ON COLUMN TB_BIO_RELIEF.ABSTRCT_DADDR IS '초본상세주소';
   COMMENT ON COLUMN TB_BIO_RELIEF.FRST_APLY_YN IS '최초신청여부';
   COMMENT ON COLUMN TB_BIO_RELIEF.FRST_APLY_NO IS '최초신청번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.APLY_YMD IS '신청일자';
   COMMENT ON COLUMN TB_BIO_RELIEF.RCPT_YMD IS '접수일자';
   COMMENT ON COLUMN TB_BIO_RELIEF.PRGRE_STUS_CD IS '진행상태코드';
   COMMENT ON COLUMN TB_BIO_RELIEF.SIGN_CN IS '서명내용';
   COMMENT ON COLUMN TB_BIO_RELIEF.MNGR_REG_YN IS '관리자등록여부';
   COMMENT ON COLUMN TB_BIO_RELIEF.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_RELIEF.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_RELIEF.MDFCN_YMD IS '수정일자';
   
COMMENT ON TABLE TB_BIO_RELIEF_HST IS '살생물_구제급여신청이력';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.HST_NO IS '이력번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLY_NO IS '신청번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLY_SE_CD IS '신청구분코드';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLY_KND_CD IS '신청종류코드';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLY_RESN IS '신청사유';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.SUFRER_NO IS '피해자번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_NO IS '신청자번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_NM IS '신청자명';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_BRDT IS '신청자생년월일';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_RRNO IS '신청자주민등록번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_TELNO IS '신청자전화번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_MBTEL_NO IS '신청자휴대전화번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_EML_ADDR IS '신청자이메일주소';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_ZIP IS '신청자우편번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_ADDR IS '신청자주소';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLCNT_DADDR IS '신청자상세주소';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.SUFRER_REL_CD IS '피해자관계코드';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.DMGE_PRDUCT_CD IS '피해제품코드';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.DMGE_PRDUCT_CN IS '피해제품내용';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_SBMSN_YN IS '제품제출여부';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_SBMSN_RESN IS '제품제출사유';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_PRPS IS '제품사용목적';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_SE IS '제품사용구분';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_PLCE IS '제품사용장소';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_MTHD IS '제품사용방법';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_IDNTY_YN IS '제품확인여부';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_BGNG_YMD IS '제품사용시작일자';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_END_YMD IS '제품사용종료일자';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_BGNG_HOUR IS '제품사용시작시';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_END_HOUR IS '제품사용종료시';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USE_CUNT_CN IS '제품사용횟수내용';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRDUCT_USGQTY_CN IS '제품사용량내용';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.DMGE_DISS_NM IS '피해질환명';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.ETC_OPINION_CN IS '기타의견내용';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.BANK_NM IS '은행명';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.DPSTR_NM IS '예금주명';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.ACTNO IS '계좌번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.DTH_YN IS '사망여부';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.DTH_YMD IS '사망일자';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.DMGE_RCOGN_YN IS '피해인정여부';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRIORD_BRVFM_NM IS '선순위유족명';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRIORD_BRVFM_REL_CD IS '선순위유족관계코드';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.ASGNR_NM IS '양도인명';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.ASGNR_REL_CD IS '양도인관계코드';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.ABSTRCT_ZIP IS '초본우편번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.ABSTRCT_ADDR IS '초본주소';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.ABSTRCT_DADDR IS '초본상세주소';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.FRST_APLY_YN IS '최초신청여부';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.FRST_APLY_NO IS '최초신청번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.APLY_YMD IS '신청일자';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.RCPT_YMD IS '접수일자';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.PRGRE_STUS_CD IS '진행상태코드';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.SIGN_CN IS '서명내용';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.MNGR_REG_YN IS '관리자등록여부';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.RGTR_NO IS '등록자번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.REG_YMD IS '등록일자';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.MDFR_NO IS '수정자번호';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.MDFCN_YMD IS '수정일자';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.LOG_TY IS 'LOG유형';
   COMMENT ON COLUMN TB_BIO_RELIEF_HST.HST_YMD IS '이력일자';
*/   

